# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Gibbons
email: johngibbons10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software developer working in beautiful San Francisco, CA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johngibbons.github.io" # the base hostname & protocol for your site
twitter_username: TheNotoGIB
github_username:  johngibbons

# Build settings
markdown: kramdown
timezone: 'America/Los_Angeles'
